### ISSUE TITLE
Saving Session data seems to be broken.

### ISSUE THREAD

**Issue by AldersTech** [TShoKT/Django-DiscordOauth2#2]
I have been doing tests and notice if someone happens to refresh once to quick after authenticating, or switch between pages too quickly then it will ask you to once again re authenticate.

Let me know if you have any trouble understanding.

**Comment by AldersTech** [comment]
It seems as though sessions data is not saving properly, I looked into other frameworks and am not sure what I should do here

**Comment by TShoKT** [comment]
Hi CodeInFilth, thanks for the issue, I tested it several times, there was no problem, I think the problem is with your browser, because the session can't be deleted ,broke or will have a problem by quickly switching the tabs
